### ISSUE TITLE
Intuition on Table 2 results residual connections

### ISSUE THREAD

**Issue by FabianRitter** [nverma1/merging-text-transformers#5]
Hi Neha, congrats for this very interesting work. I read your paper thoroughly and I found the motivations very clear yet I can't grasp about the difficulties of permuting the residual connections. From your results it appears that just using an Identity is the best approach. Have you had more intuitions on why this is the case? I would love to hear more about it.
Thanks again!

**Comment by nverma1** [comment]
Hi Fabian, thanks for your comments and your interest!

My intuition behind this result is two-fold. The first is that perhaps the residual connections have some sort of neuron ordering preservation effect via re-adding the prior layer's result. This may be especially the case with the input and output embeddings tied. These embeddings have a specific neuron ordering that is shared, and all intermediate layers may be "better off" preserving this ordering. 

The second is that due to the result where all residual permutations must be connected to maintain functional equivalence, trying to piece together the correct signal (Table 2) to inform this single permutation is a difficult premise. This may explain why we weren't able to recover a permutation that performs similarly to the identity as well.

**Comment by FabianRitter** [comment]
Thanks so much for the answer. Intuition 1 seems very reasonable!. The second comment I am not fully grasping it but I'll put some thought on it.
